"""Constants used throughout SHAREM."""

from enum import IntEnum

RED = "\u001b[31;1m"
GREEN = "\u001b[32;1m"
YELLOW = "\u001b[33;1m"
BLUE = "\u001b[34;1m"
MAGENTA = "\u001b[35;1m"
CYAN = "\u001b[36;1m"
WHITE = "\u001b[37m"
RESET = "\u001b[0m"

SHELLCODE_LABEL = "shellcode"
SHELLCODE_DECODED_BODY_LABEL = "decoded body"
SHELLCODE_DECODED_STUB_LABEL = "decoded stub"
SHELLCODE_DECODED_FULL_LABEL = "decoded shellcode (full)"


class ModeEnum(IntEnum):
    """Enum for input mode."""

    UNENCRYPTEDSHELL = 0x0
    DECODERSHELL = 0x1
    UNENCRYPTEDBODYSHELL = 0x3
    SAMPLE = 0x4
    ALLOBJECT = 0x5


SYSCALL_NAME_STRINGS = [
    "NA  Windows XP",
    "\txp1  SP1",
    "\txp2  SP2",
    "NA  Windows Server 2003",
    "\ts30  SP0",
    "\ts32  SP2",
    "\ts3r  R2",
    "\ts3r2  R2 SP2",
    "NA  Windows Vista",
    "\tv0  SP0",
    "\tv1  SP1",
    "\tv2  SP2",
    "NA  Windows Server 2008",
    "\ts80  SP0",
    "\ts82  SP2",
    "\ts8r  R2",
    "\ts8r1  R2 SP1",
    "NA  Windows 7",
    "\tw70  SP0",
    "\tw71  SP1",
    "NA  Windows Server 2012",
    "\ts120  SP0",
    "\ts12r  R2",
    "NA  Windows 8",
    "\tw80  8.0",
    "\tw81  8.1",
    "NA  Windows 10",
    "\tr0  release 1507",
    "\tr1  release 1511",
    "\tr2  release 1607",
    "\tr3  release 1703",
    "\tr4  release 1709",
    "\tr5  release 1803",
    "\tr6  release 1809",
    "\tr7  release 1903",
    "\tr8  release 1909",
    "\tr9  release 2004",
    "\tr10  release 20H2",
    "\tr11  release 21H1",
    "\tr12  release 21H2",
    "\tr13  release 22H2",
    "NA  Windows 11",
    "\tb1  21H2",
    "\tb2  22H2",
]

LIST_OF_LABELS = [
    "Searching for disassembly",
    "Searching for fstenv instructions",
    "Searching for push ret instructions",
    "Searching for call pop instructions",
    "Searching for heaven's gate instructions",
    "Searching for Windows syscall instructions",
    "Searching for PEB walking instructions",
]
DOS_PATTERNS = {
    "This program cannot be run in DOS mode",
    "This program must be run under Win32",
    "This program requires Microsoft Windows",
    "This program cannot be run in a DOS session",
    "This program must be run under Microsoft Windows",
    "This is a Windows",
    "This program cannot run in DOS mode",
    "This program must be run under Win64",
    "This program requires OS/2 Presentation Manager",
    "this is a Windows NT (own RTL) dynamic link library",
    "this is a Windows NT dynamic link library",
    "This program must be run under OS/2",
    "this is an OS/2 16-bit dynamic link library",
    "This is a Win32 program",
    "This program cannot be run in DOS mode",
    "this is an OS/2 32-bit dynamic link library",
    "this is a Windows 16-bit dynamic link library",
    "this is a Windows NT character-mode executable",
    "This is a Windows program, you cannot run it in DOS",
    "this is an OS/2 32-bit executable",
    "this is a Windows NT windowed executable",
    "this is an OS/2 linear extended dynamic link library",
    "this is a DOS/4G dynamic link library",
    "this is an OS/2 and eComStation dynamic link library",
    "this is a Windows NT character-mode dynamic link lib",
    "this is a Windows 16-bit executable",
    "This program cannot run in DOS mode",
    "This program cannot be run in DOS",
    "This www.verypdf.combe run in DOS mode",
    "this is an OS/2 dynamic link library",
    "this is a Windows dynamic link library",
    "This is a Windows 95 dynamic link library",
    "this is an OS/2 linear extended executable",
    "This program requires Phar Lap’s 286|DOS-Extender",
    "this is a PE dynamic link library",
    "this is a Windows 95 executable",
    "This program requires Microsoft Windows",
    "This is a TrueType font, not a program",
    "This program requires OS/2",
    "this is a Windows executable",
    "this is a Windows NT windowed dynamic link library",
    "This www.verypdf.com e run in DOS mode",
    "This is an OS/2 executable module",
    "this is a PE executable",
    "this is a 32 bit OS/2 Configurator executable",
    "This program requires OS/2",
    "This program must be run under Win32",
    "This program cannot be ran in DOS mode",
    "This is a Windows font file",
    "This Salford program requires Win32 or Win32s",
    "This program runs under Win32/win64",
    "this is a win32 executable",
    "this is a Windows NT executable",
    "This program requires Microsoft Windows",
    "This is a SNAP binary portable dynamic link library",
    "this program cannot be run in dos mode",
    "this program must be run under win32",
    "this program requires microsoft windows",
    "this program cannot be run in a dos session",
    "this program must be run under microsoft windows",
    "this is a windows",
    "this program cannot run in dos mode",
    "this program must be run under win64",
    "this program requires os/2 presentation manager",
    "this is a windows nt (own rtl) dynamic link library",
    "this is a windows nt dynamic link library",
    "this program must be run under os/2",
    "this is an os/2 16-bit dynamic link library",
    "this is a win32 program",
    "this program cannot be run in dos mode",
    "this is an os/2 32-bit dynamic link library",
    "this is a windows 16-bit dynamic link library",
    "this is a windows nt character-mode executable",
    "this is a windows program, you cannot run it in dos",
    "this is an os/2 32-bit executable",
    "this is a windows nt windowed executable",
    "this is an os/2 linear extended dynamic link library",
    "this is a dos/4g dynamic link library",
    "this is an os/2 and ecomstation dynamic link library",
    "this is a windows nt character-mode dynamic link lib",
    "this is a windows 16-bit executable",
    "this program cannot run in dos mode",
    "this program cannot be run in dos",
    "this www.verypdf.combe run in dos mode",
    "this is an os/2 dynamic link library",
    "this is a windows dynamic link library",
    "this is a windows 95 dynamic link library",
    "this is an os/2 linear extended executable",
    "this program requires phar lap’s 286|dos-extender",
    "this is a pe dynamic link library",
    "this is a windows 95 executable",
    "this program requires microsoft windows",
    "this is a truetype font, not a program",
    "this program requires os/2",
    "this is a windows executable",
    "this is a windows nt windowed dynamic link library",
    "this www.verypdf.com e run in dos mode",
    "this is an os/2 executable module",
    "this is a pe executable",
    "this is a 32 bit os/2 configurator executable",
    "this program requires os/2",
    "this program must be run under win32",
    "this program cannot be ran in dos mode",
    "this is a windows font file",
    "this salford program requires win32 or win32s",
    "this program runs under win32/win64",
    "this is a win32 executable",
    "this is a windows nt executable",
    "this program requires microsoft windows",
    "this is a snap binary portable dynamic link library",
}
